spring:
  datasource:
    todos:
      url: jdbc:postgresql://localhost:5432/first_database
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    topics:
      url: jdbc:postgresql://localhost:5432/second_database
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect